### ISSUE TITLE
Resolve compatibility with Firefox 52 / current Tor Browser

### ISSUE THREAD

**Issue by nym-zone** [nym-zone/block_cloudflare_mitm_fx#2]
Priority: High

[a.m.o](https://addons.mozilla.org/en-US/firefox/addon/block-cloudflare-mitm-attack/) reports that this requires at least Firefox 53.  It says it is not compatible with my browser, Tor Browser (currently based on Firefox 52 ESR).  I am uploading this to Github; but I can’t even test it until the compatibility issue is resolved.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
"AMO (Add-ons Mozilla Org) won't sign new SDK, XUL or XPCOM extensions for Firefox desktop with the release of Firefox 53". Impossible to sign legacy add-on.

**Comment by ghost** [comment]
Did you tried 1.0.7?
