### ISSUE TITLE
Use error/warning pages

### ISSUE THREAD

**Issue by nym-zone** [nym-zone/block_cloudflare_mitm_fx#3]
Priority: high

When Cloudflare is detected, the original add-on redirects requests to `0.0.0.0`.  It would be better to use error/warning pages, patterned after Firefox’s handling of *e.g.* unverifiable TLS certificates.  A variable should control whether this throws an error, or a warning with a button which permits the user to proceed.  Eventually, this can be tied to “security levels” as discussed in [Tor Browser Bug #24351](https://trac.torproject.org/projects/tor/ticket/24351).

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
fixed in v1.0.1.1

**Comment by ghost** [comment]
fixed in v1.0.1
