### ISSUE TITLE
Add bypass/whitelist function

### ISSUE THREAD

**Issue by nym-zone** [nym-zone/block_cloudflare_mitm_fx#4]
Implementation-wise, this should start with some variable which can easily be refactored into another API.  This will facilitate potential future integration with Torbutton, or other popular add-ons such as Noscript.

In my personal opinion, the purpose of this add-on is to facilitate user information and empowerment.  I, personally, do not wish to forbid access to Cloudflared sites; rather, I want to make the browser’s lock icon stop lying to me.  Part of the problem with Cloudflare is that in normal web use, it’s invisible; nothing even tells the user that there is an active MITM attack in progress.  The browser should immediately cut the connection when it detects *any* MITM attack; but it should permit well-informed users to override this behaviour, just as it does with unverifiable certificates.

For example, I desire to whitelist Bitcointalk.org.  It’s a public forum, where I send little which is not published anyway; and the administrator, theymos, was sufficiently honest to characterize his move behind Cloudflare as [“(for now) admitting defeat”](https://bitcointalk.org/index.php?topic=2485318.msg25449826#msg25449826) (*WARNING: Cloudflared link;* boldface added):

>With regret, I am (for now) admitting defeat on the DDoS front, and we will soon be using using Cloudflare to protect against DDoS attacks. [...]
>
>I really don't believe in willingly putting a man-in-the-middle in your HTTPS like this, but my homebrew DDoS mitigation has been one of my biggest time sinks for the last 6 months or so, and the necessary servers are still pretty expensive. If I had more manpower, then I would prioritize maintaining our own DDoS protection, but with me as the only sysadmin and current-software developer, it's become unsustainable.
>
>I especially dislike Cloudflare, which I'm almost certain is basically owned by US intelligence agencies. [...]
>
>**The Internet is seriously flawed if everyone needs to huddle behind these huge centralized anti-DDoS companies in order to survive...**
>
>The security implications are that Cloudflare can read everything you send to or receive from the server, including your cleartext password and any PMs you send or look at.

That’s the right attitude.  Such sysadmins should be supported, and helped in any efforts to dump Cloudflare.  Meanwhile, users should have the freedom to choose their own risks.  It should go without saying that the policy MUST be default-deny for all detected connections to Cloudflare—then let the user decide; I myself boycott almost all Cloudflared sites *which I know about*.

Additionally, I think it’s reasonable to whitelist Cloudflare.com.  Any of your traffic to `*.cloudflare.com` can be read by Cloudflare—*duh*.  For those who care about this issue, it’s useful to occasionally peruse Cloudflare’s blog for the latest evil.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
fixed in v1.0.1.1

**Comment by CloudBurn** [comment]
Whitelisting is not easy currently. The extension warning page does not show a button to add the infected site to the whitelist (not even one to proceed to the site anyway with an implicit temporary whitelisting). Such buttons could be added.

Even if those buttons were available, often many infected third party domains would have to be manually added to the whitelist before being able to visit the infected site, and one would need to either add all third-party domains or make long tests to know which third-party domains are infected too. This is not practical. Possible solution : have the (temporary and/or permanent) whitelisting buttons on the warning page also whitelist third-party domains.

This leads to the idea of having an extension toolbar button that could list which domains or requests are infected on the current whitelisted site. It could also allow to globally disable the extension and go to the settings page, for easier access to the whitelist for example.

To make things even more practical, there could even be an optional mode where the extension does not throw obtrusive warnings on every infected site but only has the extension button appearance changing to a warning sign.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
@CloudBurn @nym-zone Whitelist is already added in v1.0.1. @nym-zone, how about importing v1.0.3(current latest) here?

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
Here's current options menu, if you don't have FF57/58.

>[Whitelist]
>1. Add FQDN you want to ignore. One FQDN per line. Click "Save".
>2. Open new tab and visit whitelisted website.
>( box )
>
>[Advanced]
>[ ] Also detect and block Incapsula MiTM
>[ ] Also detect and block Google's Project Shield MiTM
>[ ] Ignore http:// resource (not recommend)
>[ ] Ignore CSS|JS|Image resource (not recommend)

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
> The extension warning page does not show a button to add the infected site to the whitelist
> with an implicit temporary whitelisting. Such buttons could be added.

It's difficult because internet webpage can't access to add-on's JS directly. (add-on can access to website)

> often many infected third party domains would have to be manually added
> to the whitelist before being able to visit the infected site,

Try "Ignore CSS|JS|Image resource (not recommend)".
Most of 3rd party connection are css, js, or image requests.

> It could also allow to globally disable the extension and go to the settings page,
> for easier access to the whitelist for example

Good idea. v1.0.4.

> there could even be an optional mode where the extension does not throw obtrusive warnings on
>every infected site but only has the extension button appearance changing to a warning sign

Another good idea. v1.0.4. Soon.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
@nym-zone so please reupload the source to github when v1.0.4 released.

**Comment by ghost** [comment]
v1.0.5's exception button will be useful.
